# Configuración del Sitio

# Importar el tema
theme: jekyll-theme-chirpy

# El idioma de la página web › http://www.lingoes.net/en/translator/langcode.htm
# Si tiene el mismo nombre que uno de los archivos en la carpeta `_data/locales`, el idioma del layout también cambiará,
# de lo contrario, el idioma del layout usará el valor por defecto 'en'.
lang: es-ES

# Cambia a tu zona horaria › https://kevinnovak.github.io/Time-Zone-Picker
timezone: America/Mexico_City

# Configuraciones de jekyll-seo-tag › https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md
# ↓ --------------------------

title: Luis Francisco # el título principal

tagline: Tecnico en electricidad y futuro programador. # se mostrará como el subtítulo

description: >- # utilizado por el meta seo y el feed atom
  Técnico en electricidad con una sólida formación en ciencias de la computación

# Completa con el protocolo y el nombre de host de tu sitio.
# ej. 'https://username.github.io', nota que no termina con una '/'.
url: "https://t4dokiary.github.io"

github:
  username: t4dokiary # cambia a tu nombre de usuario de github

twitter:
  username: TadokiaryKazuto # cambia a tu nombre de usuario de twitter

social:
  # Cambia a tu nombre completo.
  # Se mostrará como el autor por defecto de los posts y el propietario de los derechos de autor en el Footer
  name: Luis Francisco Matlalcuatzi Gonzalez
  email: luis.matlalcuatzi@gmail.com # cambia a tu dirección de correo electrónico
  links:
    # El primer elemento sirve como el enlace del propietario de los derechos de autor
    # Descomenta abajo para agregar más enlaces sociales
    - https://www.linkedin.com/in/luis-francisco-matlalcuatzi-gonzalez/
    - https://twitter.com/TadokiaryKazuto # cambia a tu página de inicio de twitter
    - https://github.com/t4dokiary # cambia a tu página de inicio de github
    - https://www.facebook.com/whiichito

# Configuración de verificación de sitio de Google (desactivada por defecto)
google_site_verification:
  # Activa o desactiva la verificación de sitio de Google
  enabled: false
  # Completa con tu cadena de verificación de Google
  verification_code: "" # Inserta aquí tu cadena de verificación

# ↑ --------------------------
# Fin de las configuraciones de `jekyll-seo-tag`

# Configuración de Google Analytics (desactivada por defecto)
google_analytics:
  # Activa o desactiva Google Analytics
  enabled: true
  # Completa con tu ID de Google Analytics
  id: "G-9FFYFGXYJ7" # Inserta aquí tu ID de Google Analytics

# Preferencia de esquema de color.
#
# Nota: Mantener vacío seguirá la preferencia de color del sistema por defecto,
# y habrá un interruptor para cambiar el tema entre oscuro y claro
# en la parte inferior izquierda de la barra lateral.
#
# Opciones disponibles:
#
#     light  - Usa el esquema de color claro
#     dark   - Usa el esquema de color oscuro
#
theme_mode: # [light|dark]

# El punto final CDN para imágenes.
# Ten en cuenta que una vez asignado, la url CDN
# se agregará a todas las rutas de imágenes (avatar del sitio e imágenes de los posts) que comiencen con '/'
#
# ej. 'https://cdn.com'
img_cdn:

# el avatar en la barra lateral, soporta recursos locales o CORS
avatar: "assets/avatar/avatar.jpg"

# tipo booleano, el interruptor global para TOC en los posts.
toc: true

comments:
  active: # El interruptor global para comentarios en los posts, ej., 'disqus'.  Mantener vacío significa desactivar
  # Las opciones activas son las siguientes:
  disqus:
    shortname: # completa con el shortname de Disqus. › https://help.disqus.com/en/articles/1717111-what-s-a-shortname
  # Configuraciones de utterances › https://utteranc.es/
  utterances:
    repo: # <gh-username>/<repo>
    issue_term: # < url | pathname | title | ...>
  # Opciones de Giscus › https://giscus.app
  giscus:
    repo: # <gh-username>/<repo>
    repo_id:
    category:
    category_id:
    mapping: # opcional, por defecto a 'pathname'
    input_position: # opcional, por defecto a 'bottom'
    lang: # opcional, por defecto al valor de `site.lang`
    reactions_enabled: # opcional, por defecto al valor de `1`

# Recursos estáticos autoalojados, opcional › https://github.com/cotes2020/chirpy-static-assets
assets:
  self_host:
    enabled: # tipo booleano, mantener vacío significa falso
    # especifica el entorno de Jekyll, vacío significa ambos
    # solo funciona si `assets.self_host.enabled` es 'true'
    env: # [development|production]

pwa:
  enabled: true # la opción para la característica PWA

paginate: 10

# La URL base de tu sitio
baseurl:

# ------------ Las siguientes opciones no se recomienda modificar ------------------

# Configuración de Kramdown, el procesador de Markdown utilizado por Jekyll
kramdown:
  syntax_highlighter: rouge # Utiliza Rouge para el resaltado de sintaxis
  syntax_highlighter_opts: # Opciones de Rouge › https://github.com/jneen/rouge#full-options
    css_class: highlight # Clase CSS para el resaltado
    # default_lang: console
    span:
      line_numbers: false # Números de línea en bloques de código en línea
    block:
      line_numbers: true # Números de línea en bloques de código
      start_line: 1 # Número de línea inicial

# Configuración de colecciones personalizadas
collections:
  tabs:
    output: true # Genera archivos para cada elemento en la colección 'tabs'
    sort_by: order # Ordena por el campo 'order'

# Valores predeterminados para diferentes tipos de contenidos
defaults:
  - scope:
      path: "" # Una cadena vacía aquí significa todos los archivos en el proyecto
      type: posts
    values:
      layout: post
      comments: true # Habilita comentarios en los posts.
      toc: true # Muestra la columna TOC en los posts.
      # NO modificar el siguiente parámetro a menos que estés seguro de actualizar
      # el código de todos los demás enlaces de posts en este proyecto.
      permalink: /Articulos/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs # ver `site.collections`
    values:
      layout: page
      permalink: /:title/
  - scope:
      path: assets/img/favicons
    values:
      swcache: true
  - scope:
      path: assets/js/dist
    values:
      swcache: true

# Configuración de Sass, el procesador de CSS
sass:
  style: compressed # Estilo de compresión de CSS

# Configuración para comprimir HTML
compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development] # Ignora la compresión en el entorno de desarrollo

# Excluir archivos y carpetas del sitio generado
exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - rollup.config.js
  - package*.json

# Configuración para jekyll-archives, crea archivos para categorías y etiquetas
jekyll-archives:
  enabled: [categories, tags] # Habilita archivos para categorías y etiquetas
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /etiquetas/:name/ # Estructura de enlace permanente para etiquetas
    category: /categorias/:name/ # Estructura de enlace permanente para categorías
